from hermes_pulse.models import TriggerProfile


TRIGGER_REGISTRY = {
    "digest.morning.default": TriggerProfile(
        id="digest.morning.default",
        family="scheduled",
        event_type="digest.morning",
        collection_preset="broad_day_start",
        output_mode="digest",
        action_ceiling=1,
        cooldown_minutes=360,
        quotas={"feed_items": 3, "resurface_items": 3, "people_bundles": 2},
    ),
    "digest.evening.default": TriggerProfile(
        id="digest.evening.default",
        family="scheduled",
        event_type="digest.evening",
        collection_preset="broad_day_end",
        output_mode="digest",
        action_ceiling=1,
        cooldown_minutes=360,
        quotas={"feed_items": 3, "resurface_items": 3, "people_bundles": 2},
    ),
    "calendar.leave_now.default": TriggerProfile(
        id="calendar.leave_now.default",
        family="event",
        event_type="calendar.leave_now",
        collection_preset="calendar_leave_now",
        output_mode="warning",
        action_ceiling=1,
        cooldown_minutes=15,
    ),
    "mail.operational.default": TriggerProfile(
        id="mail.operational.default",
        family="event",
        event_type="mail.operational",
        collection_preset="mail_operational",
        output_mode="warning",
        action_ceiling=2,
        cooldown_minutes=30,
    ),
    "shopping.replenishment.default": TriggerProfile(
        id="shopping.replenishment.default",
        family="event",
        event_type="shopping.replenishment",
        collection_preset="shopping_replenishment",
        output_mode="action_prep",
        action_ceiling=2,
        cooldown_minutes=720,
    ),
    "feed.update.default": TriggerProfile(
        id="feed.update.default",
        family="event",
        event_type="feed.update",
        collection_preset="known_source_delta",
        output_mode="nudge",
        action_ceiling=1,
        cooldown_minutes=60,
    ),
    "feed.update.expert_depth": TriggerProfile(
        id="feed.update.expert_depth",
        family="event",
        event_type="feed.update",
        collection_preset="known_source_deep_dive",
        output_mode="deep_brief",
        action_ceiling=1,
        cooldown_minutes=240,
    ),
    "feed.update.source_audit": TriggerProfile(
        id="feed.update.source_audit",
        family="event",
        event_type="feed.update",
        collection_preset="known_source_delta",
        output_mode="source_audit",
        action_ceiling=1,
        cooldown_minutes=120,
    ),
    "location.arrival.default": TriggerProfile(
        id="location.arrival.default",
        family="event",
        event_type="location.arrival",
        collection_preset="location_arrival",
        output_mode="mini_digest",
        action_ceiling=1,
        cooldown_minutes=30,
    ),
    "location.dwell.default": TriggerProfile(
        id="location.dwell.default",
        family="event",
        event_type="location.dwell",
        collection_preset="location_dwell",
        output_mode="nudge",
        action_ceiling=1,
        cooldown_minutes=60,
    ),
    "calendar.gap_window.default": TriggerProfile(
        id="calendar.gap_window.default",
        family="event",
        event_type="calendar.gap_window",
        collection_preset="calendar_gap_window",
        output_mode="mini_digest",
        action_ceiling=1,
        cooldown_minutes=30,
    ),
    "review.trigger_quality.default": TriggerProfile(
        id="review.trigger_quality.default",
        family="review",
        event_type="review.trigger_quality",
        collection_preset="trigger_quality_audit",
        output_mode="source_audit",
        action_ceiling=0,
        cooldown_minutes=1440,
    ),
}


def get_trigger_profile(profile_id: str) -> TriggerProfile:
    return TRIGGER_REGISTRY[profile_id]
